name: Test npm Auth

on:
  push:
    branches:
      - dev

jobs:
  test-auth:
    runs-on: ubuntu-latest

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
          scope: '@codepenguin'

      - name: Install dependencies
        run: npm ci

      - name: Debug Node & npm
        run: |
          node -v
          npm -v

      - name: Check package info
        run: |
          npm pkg get name
          npm pkg get version

      - name: Verify npm authentication
        run: npm whoami

      - name: Check registry
        run: npm config get registry